### ISSUE TITLE
CraftQL compatibility

### ISSUE THREAD

**Issue by tinchalamo** [dukt/videos-docs#3]
Possible to add [compatibility with CraftQL](https://github.com/markhuot/craftql#third-pary-field-support) so we can surface URL and title via a GraphQL endpoint?

**Comment by tinchalamo** [comment]
Just wanted to bump this up and see if it was something that might be added before the launch of Craft 3 GA.

**Comment by benjamindavid** [comment]
Thanks @tinchalamo, will look into it!

I've created a [feature request](https://github.com/dukt/videos/issues/10) on [dukt/videos](https://github.com/dukt/videos) as this repo is mostly aimed at documentation.

**Comment by slaymantis** [comment]
Hi has this been looked at yet? I am also trying to access it through GraphQL in 2021
